### ISSUE TITLE
"More pictures to color!" button not working on iPad

### ISSUE THREAD

**Issue by mel-gross** [carbonology/ColoringBook#21]

**Comment by mel-gross** [comment]
They actually work the buttons are just super small and you can hardly see it (won't click unless you know)

![image from ios](https://user-images.githubusercontent.com/32377080/44690185-ec515600-aa27-11e8-93d3-c068f33281bc.png)

**Comment by wwwApp** [comment]
Buttons are not there on mobile - but it works if you click the place where the buttons are supposed to be displayed
