### ISSUE TITLE
Beta Feedback

### ISSUE THREAD

**Issue by jdyuanglee** [carbonology/ColoringBook#26]
Print and share functions are incomplete. Some images were saved as txt file. Some svg's grouping are confusing

**Comment by jdyuanglee** [comment]
<img width="599" alt="screen shot 2018-08-27 at 6 27 32 pm" src="https://user-images.githubusercontent.com/32436222/44689866-f4f55c80-aa26-11e8-9b02-61fc16dccff9.png">

**Comment by jdyuanglee** [comment]
Bash scripting is pretty good. UI is friendly to all users.

**Comment by carbonology** [comment]
Fixed, removed print and share buttons #20, save button now works correctly #22
