### ISSUE TITLE
Nothing works on the phone

### ISSUE THREAD

**Issue by katy320** [carbonology/ColoringBook#31]
The phone version of this webpage shows ALL the un-clickable coloring pages, and BOTH the nonfunctional color pickers.

**Comment by carbonology** [comment]
We dont see this on our end. Can you send your specs and the link you are using?

**Comment by katy320** [comment]
![img_8006](https://user-images.githubusercontent.com/24617259/44886826-d4333e00-ac96-11e8-8d0f-813066504839.PNG)

This is from my iPHONE 5SE Safari browser
