### ISSUE TITLE
This is how the website looks on an iPhone 6

### ISSUE THREAD

**Issue by mel-gross** [carbonology/ColoringBook#45]
-no buttons to go between images and small logo
![image from ios 1](https://user-images.githubusercontent.com/32377080/44690799-26235c00-aa2a-11e8-9ea4-6c24c331b6c2.png)
![image from ios 2](https://user-images.githubusercontent.com/32377080/44690800-26bbf280-aa2a-11e8-8978-1314532a3ee5.png)

**Comment by carbonology** [comment]
Fixed here https://github.com/carbonology/ColoringBook/commit/ca7c5a260e333d28da13366677e40859293f97a2
